### ISSUE TITLE
Default cmd for api doesn't work

### ISSUE THREAD

**Issue by guillaumevincent** [redhat-cip/dci-dev-env#2]
`docker-compose -f dci.yml up` doesn't work because `runtestserver.py` expect some initial data.

IMO we should add an entrypoint, create `dci` database and run alembic migrations when we start API.

<details>

```
api_1        | Traceback (most recent call last):
api_1        |   File "/opt/dci-control-server/scripts/runtestserver.py", line 22, in <module>
api_1        |     dci_app = app.create_app(conf)
api_1        |   File "/opt/dci-control-server/dci/app.py", line 84, in create_app
api_1        |     dci_config.sanity_check(conf)
api_1        |   File "/opt/dci-control-server/dci/dci_config.py", line 67, in sanity_check
api_1        |     row = db_conn.execute(query_team_admin_id).fetchone()
api_1        |   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
api_1        |     return meth(self, multiparams, params)
api_1        |   File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
api_1        |     return connection._execute_clauseelement(self, multiparams, params)
api_1        |   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
api_1        |     compiled_sql, distilled_params
api_1        |   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
client_1     | 219 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
api_1        |     context)
api_1        |   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
dcidevenv_doc_1 exited with code 0
api_1        |     exc_info
api_1        |   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
dcidevenv_dbwatcher_1 exited with code 0
api_1        |     reraise(type(exception), exception, tb=exc_tb)
api_1        |   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
api_1        |     context)
api_1        |   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
api_1        |     cursor.execute(statement, parameters)
api_1        | sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "teams" does not exist
api_1        | LINE 2: FROM teams 
api_1        |              ^
api_1        |  [SQL: 'SELECT teams.id, teams.created_at, teams.updated_at, teams.etag, teams.name, teams.country, teams.email, teams.notification, teams.state \nFROM teams \nWHERE teams.name = %(name_1)s'] [parameters: {'name_1': 'admin'}]
dcidevenv_api_1 exited with code 1
```

</details>

**Comment by guillaumevincent** [comment]
Fixed
